### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by HengerLi** [AI-secure/CRFL#1]
Hi, greeting! I spotted an issue when I try to reproduce the experiment on Google Colab, torch.cuda.is_available() shows True, but torch detect no CUDA GPUs. Here is the full log:
Traceback (most recent call last):
  File "main.py", line 141, in <module>
    param.add_(helper.dp_noise(param, helper.params['sigma_param']))
  File "/content/gdrive/MyDrive/CRFL/utils/helper.py", line 78, in dp_noise
    noised_layer = torch.cuda.FloatTensor(param.shape).normal_(mean=0, std=sigma)
  File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

ps: All modules in requirements.txt have installed.
The python and torch versions are: 3.7.11 and 1.9.0+cu102

**Comment by HengerLi** [comment]
The problem solved when I reinstall torch and CUDA to the exact version the author used. Close the issue. Thanks :)
